# Generated by Django 5.2.6 on 2025-10-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_service_alter_listing_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='screens',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
