# Generated by Django 5.2.6 on 2025-10-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_screens'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='screen',
            field=models.IntegerField(),
        ),
    ]
