# Generated by Django 5.2.6 on 2025-10-09 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_listing_district_alter_listing_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='rooms',
            field=models.IntegerField(),
        ),
    ]
