# Generated by Django 5.2.6 on 2025-10-10 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_subject_remove_listing_screens_listing_nights_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='nights',
        ),
    ]
