# Generated by Django 5.2.6 on 2025-10-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_listing_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='nights',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default=''),
        ),
        migrations.AddField(
            model_name='listing',
            name='room_type',
            field=models.CharField(choices=[('Private Rooms', 'Private Rooms'), ('Semi-Private Rooms', 'Semi-Private Rooms'), ('Standard (Multi-bed) Rooms', 'Standard (Multi-bed) Rooms')], default='', max_length=50),
        ),
    ]
