# Generated by Django 5.2.6 on 2025-10-09 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_alter_listing_nights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='room_type',
            field=models.CharField(choices=[('Private Rooms', 'Private Rooms'), ('Semi-Private Rooms', 'Semi-Private Rooms'), ('Standard (Multi-bed) Rooms', 'Standard (Multi-bed) Rooms')], max_length=50),
        ),
    ]
