# Generated by Django 5.2.6 on 2025-10-09 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_alter_listing_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='nights',
            field=models.IntegerField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')]),
        ),
    ]
