# Generated by Django 5.2.6 on 2025-10-09 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_listing_nights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='nights',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='listing',
            name='room_type',
            field=models.CharField(max_length=50),
        ),
    ]
