# Generated by Django 5.2.6 on 2025-10-09 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_alter_listing_nights_alter_listing_room_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='nights',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='room_type',
        ),
    ]
